In [31]:
import numpy as np
a = [1,1,1,1,0,0,0,0,1]
a = np.array(a)
b = np.zeros(shape=(9,4))
b[:]=a.reshape(-1,1)
c = [1, 1, 0, 1, 0, 1, 0, 1, 0]
c=np.array(c)
print(b)
e = b[np.argwhere(c)[:, 0],:]
print(e)
print(e)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
